Prometheus scraper package
splunk/dlt-connect-libs pull request #9
Opened 2020-11-18 21:16 UTC by ziegfried

2020-11-30 17:19 UTC, atoulme requested changes
One typo and a question about muti-metrics regarding histograms.

2020-11-30 17:19 UTC, atoulme commented on packages/prometheus-scraper/src/convert/base.ts
> +export const convertTimestmapToHec = (ts: string | undefined, fallback: number): number => {
typo in function name

2020-11-30 17:19 UTC, atoulme commented on packages/prometheus-scraper/src/convert/collapse.ts
> +                multiMetric.measurements[metric.name] = metric.value;
Do we want to merge fields as well?

2020-11-30 17:19 UTC, atoulme commented on packages/prometheus-scraper/src/convert/collapse.ts
> +                debug('Ignoring duplicate metric name %s', metric.name);
this sounds like it would clash with histograms. If you see twice the same metric name, might be time to flush and recreate a new metric with fields.

2020-11-30 19:02 UTC, ziegfried commented on packages/prometheus-scraper/src/convert/collapse.ts
> +                multiMetric.measurements[metric.name] = metric.value;
We can only merge 2 metrics into a multi-metrics object if fields are the same.

2020-11-30 19:04 UTC, ziegfried commented on packages/prometheus-scraper/src/convert/collapse.ts
> +                debug('Ignoring duplicate metric name %s', metric.name);
In case of histogram and summary, the multiMetric object is going to be != null and won't hit this branch here.

2020-11-30 19:12 UTC, atoulme approved these changes

2020-12-01 20:48 UTC, ccordi commented on packages/prometheus-scraper/README.md
> +    for (const hecMetrics of convertedMetics) {
```suggestion
    const convertedMetrics = convertToHecMultiMetrics(scrapeResult.metrics, {
        captureTimestamp: Date.now(),
        namePrefix: 'geth',
        metadata: {
            source: 'geth:metrics:prometheus',
        },
    });

    for (const hecMetrics of convertedMetrics) {
```

2020-12-01 20:49 UTC, ccordi commented on packages/prometheus-scraper/examples/simple-scraper.ts
> +                for (const hecMetrics of convertedMetics) {
```suggestion
                const convertedMetrics = convertToHecMultiMetrics(scrapeResult.metrics, {
                    captureTimestamp: Date.now(),
                    namePrefix: 'geth',
                    metadata: {
                        host: os.hostname(),
                        source: 'geth:metrics:prometheus',
                    },
                });

                for (const hecMetrics of convertedMetrics) {
```

2020-12-01 20:50 UTC, j4ys0n approved these changes

2020-12-01 22:13 UTC, ccordi approved these changes

2020-12-01 22:17 UTC, merged